### ISSUE TITLE
eql example returns nil

### ISSUE THREAD

**Issue by joinr** [ribelo/doxa#1]
from the [pull example](https://github.com/ribelo/doxa#pull)

user> (dx/pull db {[:db/id 1] [:name :aka]})
nil ;;looks like this is expected to return {:name "Petr", :aka ["Devil" "Tupen"]}
user> (dx/pull db [:name :aka] [:db/id 1])
{:name "Petr", :aka ["Devil" "Tupen"]}

**Comment by ribelo** [comment]
Thanks, somewhere I messed up after writing the readme.
