### ISSUE TITLE
failing to commit into a db

### ISSUE THREAD

**Issue by spacegangster** [ribelo/doxa#11]
Failing to create dx into a DB
both in clojure and in shadow-cljs

Version: https://github.com/ribelo/doxa/commit/956a3244ea15bedf69f18cc74385b7c2bec5635a

Steps:
```
(def data [{:db/id 1 :name "Petr" :aka ["Devil"]}])
(def db (dx/create-dx data)) 
; {}

(type db)
;  clojure.lang.PersistentArrayMap
```
Gives no error.

Project – https://github.com/spacegangster/rf-doxa-etude

Comment
I've set up doxa as a git submodule.
I'm open to consider it's something wrong with my setup.

I'm ready to jump on a call if needed, I think that would be faster for both of us.
If that fits you – pick a time here https://calendly.com/ivan-de-lightpad/30min

**Comment by ribelo** [comment]
My social anxiety is heightened when I have to speak English. I will be happy to write to you, but I can only speak to the wall or to my dog ;)

**Comment by ribelo** [comment]
Recently when fixing a bug I didn't include the tests because the change was small, but the bug ate the parenthesis and it came out as it did

**Comment by spacegangster** [comment]
Nice one mate! All fixed 🥳🥳🥳

**Comment by spacegangster** [comment]
I can make you a PR with the github script that will run the tests automatically, if you want.

**Comment by ribelo** [comment]
Yes, please.
