### ISSUE TITLE
:one refs now normalised to vectors

### ISSUE THREAD

**Issue by stevebuik** [ribelo/doxa#17]
```clojure
(let [db (dx/create-dx [{:db/id 1 :name "ivan" :car {:db/id 10 :name "tesla"}}])]
    (map? (:car (dx/pull db [:name {:car [:name]}] [:db/id 1]))))
```

I think this might be a result of the fix to #16.  Am I going crazy or is this a regression?

I think you said that the data loaded in a txn determines the cardinality. 

In this example, :car is cardinality 1 so, when pulled, it should be returned as a map?

**Comment by ribelo** [comment]
fixed

**Comment by stevebuik** [comment]
fix confirmed in my project. thanks
