### ISSUE TITLE
commit normalisation can't handle 2 id keys

### ISSUE THREAD

**Issue by stevebuik** [ribelo/doxa#23]
Nested pull doesn't work with the form below. the id field causes Doxa to create an invalid ref.

Is this a bug that can be fixed or is using 2 ids in entities not supportable?

```clojure
(let [db (->> {:id        "10"
                 :person/id "10"
                 :name      "Enzo"
                 :car       {:id            "20"            ; << comment this out and pull works
                             :automobile/id "20"
                             :name          "Audi"}}
                (vector :dx/put)
                (dx/commit (dx/create-dx)))]
    (dx/pull db [:name {:car [:autombile/id :name]}] [:person/id "10"]))
```

**Comment by stevebuik** [comment]
In the graphql world we want to use :id everywhere.

Doxa want to use :foo/id for enhanced performance. This is good.

Ideally both can co-exist in Doxa

**Comment by ribelo** [comment]
as discussed in the slack, it is possible to explicitly declare via metadata which key is to be treated as the primary key of an entity. example in tests

**Comment by stevebuik** [comment]
confirmed working in my use-case
