### ISSUE TITLE
NPE from pull

### ISSUE THREAD

**Issue by stevebuik** [ribelo/doxa#30]
(dx/pull (dx/create-dx {}) [:*] [:id "x"])

should return nil instead of NPE

**Comment by stevebuik** [comment]
same for d/pick

**Comment by ribelo** [comment]
done

**Comment by stevebuik** [comment]
thx

**Comment by stevebuik** [comment]
this commit broke cljs compile.....

------ WARNING #1 - :ns-var-clash ----------------------------------------------
 File: /Users/steve/.gitlibs/libs/doxa/doxa/7df90318781f87242cfbf7c1bea99e955c89e3c1/src/ribelo/doxa.cljc:27:1
--------------------------------------------------------------------------------
  24 | (def q -q)
  25 | (def mq -mq)
  26 | (def pick -pick)
  27 | (def ordered-set os/ordered-set)
-------^------------------------------------------------------------------------
 Namespace ribelo.doxa.ordered-set clashes with var ribelo.doxa/ordered-set
--------------------------------------------------------------------------------
  28 | (def ordered-set? os/ordered-set?)
  29 | 
  30 | (defmulti -submit-commit (fn [_db ^clojure.lang.IPersistentVector tx] (nth tx 0)))
  31 | 
--------------------------------------------------------------------------------
