### ISSUE TITLE
d/pull doesn't return falsey value

### ISSUE THREAD

**Issue by stevebuik** [ribelo/doxa#31]
(let [db (dx/create-dx {} [{:id       1
                             :name   "Java"
                             :immutable? false}])]
      (dx/pull db [:id :name :immutable?] [:id 1]))

if you change immutable to true in db, it is returned

only in noindex branch. was returned by master pull

**Comment by ribelo** [comment]
`if-let` was used instead of `if-some`, fixed

**Comment by stevebuik** [comment]
confirm fixed via hotplate tests
